INSERT INTO public.waste_manager( CREATED_DATE,ID_ADDRESS,IS_ENABLED,LAST_MODIFIED_DATE,NIF,NOMBRE,VERSION)
VALUES (NOW(),1,TRUE,NOW(),'67579425C','MIKEL VERGARA OJEDA',0);

INSERT INTO public.waste_manager(CREATED_DATE,ID_ADDRESS,IS_ENABLED,LAST_MODIFIED_DATE,NIF,NOMBRE,VERSION)
VALUES (NOW(),2,TRUE,NOW(),'19590771S','LEONARDO ESCOBAR BARROSO',0);

INSERT INTO public.waste_manager(CREATED_DATE,ID_ADDRESS,IS_ENABLED,LAST_MODIFIED_DATE,NIF,NOMBRE,VERSION)
VALUES (NOW(),3,TRUE,NOW(),'48238069P','FRANCISCO NAVARRO NOGUERA',0);

INSERT INTO PUBLIC.WASTE_CENTER_AUTHORIZATION (AUTHORIZATION_NUMBER,ID_WASTE_MANAGER) VALUES ('565SSS789',1);
INSERT INTO PUBLIC.WASTE_CENTER_AUTHORIZATION (AUTHORIZATION_NUMBER,ID_WASTE_MANAGER) VALUES ('565222EEE',1);
INSERT INTO PUBLIC.WASTE_CENTER_AUTHORIZATION (AUTHORIZATION_NUMBER,ID_WASTE_MANAGER) VALUES ('565222EE1',3);
INSERT INTO PUBLIC.WASTE_CENTER_AUTHORIZATION (AUTHORIZATION_NUMBER,ID_WASTE_MANAGER) VALUES ('5SSSSSSE1',2);

